#!/bin/bash

set -euo pipefail

timestamp() {
	date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

quit() {
	say "${@}"
	exit 0
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v FILE_DIR ] || FILE_DIR="${BASE_DIR}/file"
[ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"

[ -d "${FILE_DIR}" ] || quit "No source files to copy (${FILE_DIR}), nothing to do."
[ -d "${DEPL_DIR}" ] || quit "No target to copy the files into (${DEPL_DIR}), nothing to do."

FILES="$(cd "${FILE_DIR}" && find . -type f | sort)"
[ -n "${FILES}" ] || quit "No source files to copy, nothing to do."

say "Copying files from [${FILE_DIR}] into [${DEPL_DIR}]..."
cd "${FILE_DIR}" || fail "Failed to CD into [${FILE_DIR}]"
tar -T <(echo -n "${FILES}") -cf - | tar -C "${DEPL_DIR}" -xvf -
for RC in "${PIPESTATUS[@]}" ; do
	[ ${RC} -eq 0 ] || fail "Failed to perform the file copy (rc=${RC})"
done
say "Setting the target files to be all-readable (but not writable)"
chmod -R a=rX "${DEPL_DIR}" || fail "Failed to set the copied files' permissions"
quit "Copy completed"
