#!/bin/bash

# Enable debugging ...
[ -v DEBUG ] || DEBUG="false"
case "${DEBUG,,}" in
	true ) DEBUG="true" ;;
	* ) DEBUG="false" ;;
esac
${DEBUG} && set -x

set -euo pipefail

fail() {
	echo -e "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v CURL_ENCRYPTION_KEY ] || fail "No CURL_ENCRYPTION_KEY value is set, cannot continue"
[ -n "${CURL_ENCRYPTION_KEY}" ] || fail "The CURL_ENCRYPTION_KEY value is empty, cannot continue"

exec openssl aes-256-cbc \
	-a -A -salt -iter 5 \
	-kfile <(echo -n "${CURL_ENCRYPTION_KEY}") 2>/dev/null
