#!/bin/bash

set -euo pipefail

timestamp() {
	date -Ins -u
}

say() {
	echo -e "$(timestamp): ${@}"
}

fail() {
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v FILE_DIR ] || FILE_DIR="${BASE_DIR}file"

say "👉 Cleaning out old checksum files..."
find "${FILE_DIR}" -type f -name '*.sum' -delete

say "👉 Rendering any missing helpers for all contents of [${FILE_DIR}]..."
COUNT=0
FAILED=()
while read FILE ; do
	say "\t👉 Processing [${FILE}]..."
	VER=""
	[ -s "${FILE}.ver" ] && VER="$(<"${FILE}.ver")"
	if render-helpers "${FILE}" "${VER}" ; then
		(( ++COUNT ))
	else
		FAILED+=("${FILE}")
	fi |& sed -e 's;^;\t\t;g'
done < <(find "${FILE_DIR}" -type f -not -name '*.sum' -not -name '*.ver' | sort)

if [ ${#FAILED[@]} -gt 0 ] ; then
	S="s"
	[ ${#FAILED[@]} -ne 1 ] || S=""
	say "Rendering failed for the following ${#FAILED[@]} file${S}:"
	for FILE in "${FAILED[@]}" ; do
		say "\t${FILE}"
	done
	fail "Rebuilding helpers failed"
fi
S="s"
[ ${COUNT} -ne 1 ] || S=""
say "✅ rendered artifact helpers (version + checksum) for ${COUNT} element${S}"
