#!/bin/bash

# Enable debugging ...
[ -v DEBUG ] || DEBUG="false"
case "${DEBUG,,}" in
	true ) DEBUG="true" ;;
	* ) DEBUG="false" ;;
esac
${DEBUG} && set -x

set -euo pipefail

fail() {
	echo -e "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

if [ -v CURL_ENCRYPTION_KEY ] && [ -n "${CURL_ENCRYPTION_KEY}" ] ; then
	# Encrypt the value
	exec openssl aes-256-cbc \
		-a -A -salt -iter 5 \
		-kfile <(echo -n "${CURL_ENCRYPTION_KEY}") 2>/dev/null
else
	# Don't encrypt anything ...
	exec cat
fi
