#!/bin/bash

set -euo pipefail
. /.functions

#
# Make sure all helper files are up-to-date
#
rebuild-helpers

#
# Update the SSL configurations
#
init_ssl

DEFAULT_PORT="443"
[ $(id -u) -eq 0 ] || DEFAULT_PORT="8443"

# Make sure we're using a correct port
set_or_default PORT
is_valid_port "${PORT}" || PORT="${DEFAULT_PORT}"

# If we're not running as root, and we're using a low port,
# add 10000 to the port so we end up on a high port
[ $(id -u) -ne 0 ] && [ ${PORT} -lt 1024 ] && (( PORT += 10000 ))

export HTTPD_PORT="${PORT}"
export HTTPD_CERT="${SSL_DIR}/cert.pem"
export HTTPD_PKEY="${SSL_DIR}/cert.key"
export HTTPD_ROOT="${FILE_DIR}"

set_or_default HTTPD_EXE "/usr/local/bin/artifacts-httpd"

eyes "Launching the Artifact server"
execute "${HTTPD_EXE}"
