#!/bin/bash

set -euo pipefail
. /.functions

#
# Update the SSL configurations
#
init_ssl

#
# Make sure all helper files are up-to-date
#
rebuild-helpers

DEFAULT_PORT="443"
[ $(id -u) -eq 0 ] || DEFAULT_PORT="8443"

# Make sure we're using a correct port
set_or_default PORT
is_valid_port "${PORT}" || PORT="${DEFAULT_PORT}"

# If we're not running as root, and we're using a low port,
# add 10000 to the port so we end up on a high port
[ $(id -u) -ne 0 ] && [ ${PORT} -lt 1024 ] && (( PORT += 10000 ))

#
# Generate the GLOBAL_SUMS value
#
GLOBAL_SUMS=""
while read CATEGORY ; do
	SUMS=()
	while read ARTIFACT ; do
		[ -f "${ARTIFACT}.sum" ] || fail "No checksum computed for [${ARTIFACT}] ... initialization failed"
		SUMS+=( "${ARTIFACT}.sum" )
	done < <(find "${CATEGORY}" -type f -not -name '*.sum' -not -name '*.ver' | sort)
	if [ ${#SUMS[@]} -gt 0 ] ; then
		read SUM REST < <(sha256sum "${SUMS[@]}")
		[ -n "${GLOBAL_SUMS}" ] && GLOBAL_SUMS+=", "
		GLOBAL_SUMS+="\"${CATEGORY##*/}\": \"${SUM}\""
	fi
done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type d | sort)

export GLOBAL_SUMS="{${GLOBAL_SUMS}}"

execute /usr/local/bin/httpuploader.py \
	--config "${UPLOADER_CFG}" \
	-p ${PORT} \
	--cert "${SSL_DIR}/cert.pem" \
	--key "${SSL_DIR}/cert.key"
