#!/bin/bash

set -euo pipefail
. /.functions

get_category_sums()
{
	local CATEGORY="${1}"
	shift

	echo "Category: ${CATEGORY}"
	for SUM in "${@}" ; do
		echo -e "$(<"${SUM}")\t${SUM%.*}"
	done
}

#
# Generate the GLOBAL_SUMS value
#
GLOBAL_SUMS=""
while read CATEGORY ; do
	SUMS=()
	while read ARTIFACT ; do
		[ -f "${ARTIFACT}.sum" ] || fail "No checksum computed for [${ARTIFACT}] ... initialization failed"
		SUMS+=( "${ARTIFACT}.sum" )
	done < <(find "${CATEGORY}" -type f -not -name '*.sum' -not -name '*.ver' | sort)
	if [ ${#SUMS[@]} -gt 0 ] ; then
		read SUM REST < <(get_category_sums "${CATEGORY}" "${SUMS[@]}" | sha256sum)
		[ -n "${GLOBAL_SUMS}" ] && GLOBAL_SUMS+=", "
		GLOBAL_SUMS+="\"${CATEGORY##*/}\": \"${SUM}\""
	fi
done < <(find "${FILE_DIR}" -mindepth 1 -maxdepth 1 -type d | sort)
exec jq -r <<< "{${GLOBAL_SUMS}}"
