#!/bin/bash

set -euo pipefail
. /.functions

set_or_default BASE_DIR "/app"
set_or_default FILE_DIR "${BASE_DIR}/file"

while read FILE ; do
	SUM="${FILE}.sum"
	is_file_readable "${SUM}" && SUM="$(<"${SUM}")" || SUM="(unknown)"

	VER="${FILE}.ver"
	is_file_readable "${VER}" && VER="$(<"${VER}")" || VER="(unknown)"

	echo "${FILE} ${VER} ${SUM}"
done < <( find "${FILE_DIR}" -type f -not -name '*.ver' -not -name '*.sum' -not -name '.*' | sort ) | \
	column -n "artifacts" --table-columns filename,version,checksum --json | \
	jq -r
exit 0
