#!/bin/bash

set -euo pipefail
. /.functions

set_or_default BASE_DIR "/app"
set_or_default FILE_DIR "${BASE_DIR}/file"

doing "Cleaning out old checksum files..."
find "${FILE_DIR}" -type f -name '*.sum' -delete

doing "Rendering any missing helpers for all contents of [${FILE_DIR}]..."
COUNT=0
FAILED=()
while read FILE ; do
	say "\t👉 Processing [${FILE}]..."
	VER=""
	[ -s "${FILE}.ver" ] && VER="$(<"${FILE}.ver")"
	if render-helpers "${FILE}" "${VER}" ; then
		(( ++COUNT ))
	else
		FAILED+=("${FILE}")
	fi |& sed -e 's;^;\t\t;g'
done < <(find "${FILE_DIR}" -type f -not -name '*.sum' -not -name '*.ver' | sort)

if [ ${#FAILED[@]} -gt 0 ] ; then
	S="s"
	[ ${#FAILED[@]} -ne 1 ] || S=""
	say "Rendering failed for the following ${#FAILED[@]} file${S}:"
	for FILE in "${FAILED[@]}" ; do
		say "\t${FILE}"
	done
	fail "Rebuilding helpers failed"
fi
S="s"
[ ${COUNT} -ne 1 ] || S=""
ok "Rendered artifact helpers (version + checksum) for ${COUNT} element${S}"
