#!/bin/bash

set -euo pipefail
. /.functions

set_as_boolean DEBUG
${DEBUG} && set -x

usage()
{
	echo -e "usage: ${BASH_SOURCE:-${0}} file [version]" 1>&2
	exit 1
}

[ ${#} -ge 1 ] || usage
[ ${#} -le 2 ] || usage

FILE="${1}"
require_file_readable "${FILE}"

VER=""
[ ${#} -eq 2 ] && VER="${2}"
[ -n "${VER}" ] || VER="(unknown)"

# Create the checksum file
SUM="${FILE}.sum"
SHA256="$(sha256sum < "${FILE}" | sed -e 's;\s.*$;;g' | tr -d '\n')"
doing "Creating the checksum file at [${SUM}] with [${SHA256}]"
echo -n "${SHA256}" > "${SUM}"

VMARK="${FILE}.ver"
doing "Creating the version marker at [${VMARK}] with [${VER}]..."
echo -n "${VER}" > "${VMARK}"

ok "Done"
exit 0
